version: "3.4"
services:
    dengue_db:
      build:
        context: ".."
        dockerfile: "docker/Dockerfile"
      env_file:
        - ../.env
      hostname: dengue_db
      ports:
        - "25432:25432"
      volumes:
        - ../:/Data
        - ${STAGING_DATA_DIR}:/var/lib/postgresql/data
