 # This workflow will install Postgresql dependencies and run the database demo.


name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    env:
      COMPOSE_FILE: docker/docker-compose.yml
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Check docker and docker-compose versions
      run: |
        docker-compose --version
        docker --version

    - name: Copy env_file as env
      run: |
        cp example_env_file .env

    - name: Download data from Dataverse
      run: |
        make download_demodb

    - name: Recreate container
      run: |
        make build
        make deploy
        make recreate_container
  
    - name: Destroy images
      run: |
        make remove_image_dengue_db
